### ISSUE TITLE
918+ LSI SAS driver error

### ISSUE THREAD

**Issue by valiger8779** [pocopico/4.4.180plus-modules#2]
Hi Pocopico,
Thanks for your driver modules.
Now I meet a problem that my LSI 2308 SAS HBA card cannot work normally.
The HBA card is made by Inspur,PN YZCA000227-101.
After 
insmod scsi_transport_sas.ko
insmod libsas.ko
insmod raid_class.ko
insmod mpt3sas.ko
It can be recognized by lsmod |grep -i mpt.
But the disks S.M.A.R.T are unrecognized and the system preverts building the storage pool.
How can fix this problem?
Thanks and hope your reply.

**Comment by dysf888** [comment]
> Hi Pocopico,
> Thanks for your driver modules.
> Now I meet a problem that my LSI 2308 SAS HBA card cannot work normally.
> The HBA card is made by Inspur,PN YZCA000227-101.
> After
> insmod scsi_transport_sas.ko
> insmod libsas.ko
> insmod raid_class.ko
> insmod mpt3sas.ko
> It can be recognized by lsmod |grep -i mpt.
> But the disks S.M.A.R.T are unrecognized and the system preverts building the storage pool.
> How can fix this problem?
> Thanks and hope your reply.

Hello friend, after two years, I also encountered this problem today. I want to known how to solve it?
